* This file was automatically generated by Zimpl
* var x_v1 binary;
* var x_v2 binary;
* var x_v3 binary;
* var x_v4 binary;
* minimize cost: x_v1 + x_v2 + x_v3 + x_v4;
* subto E1: x_v1 + x_v2 >= 1;
* subto E2: x_v1 + x_v3 >= 1;
* subto E3: x_v2 + x_v3 >= 1;
* subto E4: x_v1 + x_v4 >= 1;
* subto E5: x_v2 + x_v4 >= 1;
* subto E6: x_v3 + x_v4 >= 1;
NAME          toConver
ROWS
 N  OBJECTIV          
 G  E1_1              
 G  E2_1              
 G  E3_1              
 G  E4_1              
 G  E5_1              
 G  E6_1              
COLUMNS
    MARK0000  'MARKER'                 'INTORG'
    x_v1      OBJECTIV             1
    x_v1      E4_1                 1
    x_v1      E2_1                 1
    x_v1      E1_1                 1
    x_v2      OBJECTIV             1
    x_v2      E5_1                 1
    x_v2      E3_1                 1
    x_v2      E1_1                 1
    x_v3      OBJECTIV             1
    x_v3      E6_1                 1
    x_v3      E3_1                 1
    x_v3      E2_1                 1
    x_v4      OBJECTIV             1
    x_v4      E6_1                 1
    x_v4      E5_1                 1
    x_v4      E4_1                 1
    MARK0001  'MARKER'                 'INTEND'
RHS
    RHS       E1_1                 1
    RHS       E2_1                 1
    RHS       E3_1                 1
    RHS       E4_1                 1
    RHS       E5_1                 1
    RHS       E6_1                 1
BOUNDS
 LO BOUND     x_v1                 0
 UP BOUND     x_v1                 1
 LO BOUND     x_v2                 0
 UP BOUND     x_v2                 1
 LO BOUND     x_v3                 0
 UP BOUND     x_v3                 1
 LO BOUND     x_v4                 0
 UP BOUND     x_v4                 1
ENDATA
