<div id="authors">
             
    <h2><a name="zib">Current developers at ZIB</a></h2>

        <table class="desc">
	    <tr>
	      <td width="180px">
		<a href="http://www.zib.de/berthold/">Timo Berthold</a>
	      </td>
	      <td>
		Primal heuristics, further development
	      </td>
	    </tr>
	    <tr>
	      <td>
		<a href="http://www.zib.de/gamrath/">Gerald Gamrath</a>
	      </td>
	      <td>
                Column generation, further development
	      </td>
	    </tr>
	    <tr>
	      <td>
		<a href="http://www.zib.de/heinz/">Stefan Heinz</a>
	      </td>
	      <td> Solution counting, further development
	      </td>
	    </tr>
	    <tr>
	      <td>
		<a href="http://www.zib.de/en/people/staff/member.html?mail=hendel">Gregor Hendel</a>
	      </td>
	      <td>
                Student assistant
              </td>
	    </tr>
	    <tr>
	      <td>
		<a href="http://www.zib.de/koch/">Thorsten Koch</a>
	      </td>
	      <td>
                Project head
	      </td>
	    </tr>		   
	    <tr>
	      <td>
		<a href="http://www.zib.de/en/people/staff/member.html?mail=waniek">Robert Waniek</a>
	      </td>
	      <td>
                Student assistant
              </td>
	    </tr>
	    <tr>
	      <td>
		<a href="http://www.zib.de/en/people/staff/member.html?mail=michael.winkler">Michael Winkler</a>
	      </td>
	      <td>
                Student assistant
	      </td>
	    </tr>
	    <tr>
	      <td>
		<a href="http://www.zib.de/wolter/">Kati Wolter</a>
	      </td>
	      <td>
		Cutting planes, further development
	      </td>
	    </tr>
	</table>

    <h2><a name="programmers">Other developers</a></h2>

    	<table class="desc">
	    <tr>
	      <td width="180px">
		<a href="http://www.zib.de/en/people/staff/member.html?mail=achterberg">Tobias Achterberg</a>&nbsp;
	      </td>
	      <td>
		Main SCIP developer &ndash; now at <a href="http://www-01.ibm.com/software/integration/optimization/cplex-optimizer/">IBM</a>
	      </td>
	    </tr>
	    <tr>
	      <td>
		<a href="http://fauam2m.am.uni-erlangen.de/optimization/edom/staff-members/martin-alexander/prof-dr-alexander-martin.html">Alexander Martin</a>
	      </td>
	      <td>
		Developer of SIP &ndash; the predecessor of SCIP
		&ndash; now at 	<a href="http://www.uni-erlangen.org/">University of Erlangen-N&uuml;rnberg</a>	
	      </td>
	    </tr>
	    <tr>
	      <td>
		<a href="http://www.math.tu-bs.de/~pfetsch/">Marc Pfetsch</a> 
	      </td>
	      <td>
		Former project head &ndash; now at <a href="http://www.tu-braunschweig.de/">TU Braunschweig</a>
	      </td>
	      <td>
	      </td>
	    </tr>
	    <tr>
	      <td>
		<a href="http://www.math.hu-berlin.de/~stefan/">Stefan Vigerske</a>
	      </td>
	      <td>
               Mixed integer nonlinear programming
	      </td>
	    </tr>
	</table>

        <h2><a name="contributors">Contributors</a></h2>

    	<table class="desc">
           <tr>
	      <td>
		 Livio Bertacco
	      </td>
	      <td>
                 Interface to <a href="http://www.fico.com/en/Products/DMTools/Pages/FICO-Xpress-Optimization-Suite.aspx">FICO/Xpress</a>
	      </td>
	    </tr>
            <tr>
	      <td>
                <a href=" http://www.math.tu-berlin.de/coga/people/bley/">Andreas Bley</a>
	      </td>
	      <td>
                 VRP example
	      </td>
	      <td>
	      </td>
	    </tr>
            <tr>
	      <td width="180px">
		<a href="http://www.dii.uchile.cl/~daespino/">Daniel Espinoza</a> 
	      </td>
	      <td>
                 Interface to <a href="http://www2.isye.gatech.edu/~wcook/qsopt/">QSopt</a>
	      </td>
	      <td>
	      </td>
	    </tr>
            <tr>
	      <td>
                 John Forrest
	      </td>
	      <td>
                 Interface to <a href="http://www.coin-or.org/Clp/">CLP</a>
	      </td>
	      <td>
	      </td>
	    </tr>
            <tr>
	      <td>
                <a href="http://fauam2m.am.uni-erlangen.de/de/optimierung/wirtschaftsmathematik/mitarbeiter/gellermann-thorsten/thorsten-gellermann.html">Thorsten Gellermann</a>
	      </td>
	      <td>
                 Generic NLP interface
	      </td>
	      <td>
	      </td>
	    </tr>
            <tr>
	      <td>
		<a href="http://www.zib.de/gleixner/">Ambros Gleixner</a>&nbsp;
	      </td>
	      <td>
                SoPlex interface, mixed integer nonlinear programming
	      </td>
	    </tr>
	    <tr>
	      <td>
                 Bo Jensen
	      </td>
	      <td>
                 Interface to <a href="http://www.mosek.com/">MOSEK</a>
	      </td>
	      <td>
	      </td>
	    </tr>
	    <tr>
	      <td>
                 <a href="http://www.math2.rwth-aachen.de/en/mitarbeiter/kutschka/">Manuel Kutschka</a>
	      </td>
              <td>
                 Separator for {0,1/2}-cuts
	      </td>
	    </tr>
            <tr>
	      <td>
                 Michael Perregaard
	      </td>
	      <td>
                 Interface to <a href="http://www.dashoptimization.com/home/products/products_optimizer.html">FICO/Xpress</a>
	      </td>
	    </tr>
            <tr>
	      <td>
		<a href="http://www.zib.de/raack/">Christian Raack</a>
	      </td>
	      <td>
                 Separator for MCF cuts
	      </td>
	    </tr>
            <tr>
	      <td>
                 <a href="http://www.rambau.wm.uni-bayreuth.de/">J&ouml;rg Rambau</a>
	      </td>
	      <td>
                 Branch-and-Price contributions
	      </td>
	      <td>
	      </td>
	    </tr>
            <tr>
	      <td>
                 <a href="http://www.math.unipd.it/~salvagni/">Domenico Salvagnin</a>
	      </td>
	      <td>
                 Feasibility Pump 2.0
	      </td>
	      <td>
	      </td>
	    </tr>
            <tr>
	      <td>
                 <a href="http://www.math.tu-berlin.de/coga/people/jschulz/">Jens Schulz</a>
	      </td>
	      <td>
                 Scheduling plugins: cumulative and linking constraint handler, variable bounds propagator
	      </td>
	      <td>
	      </td>
	    </tr>
            <tr>
	      <td>
                 <a href="http://www.wm.uni-bayreuth.de/index.php?id=417">Cornelius Schwarz</a>
	      </td>
	      <td>
                 Queens example
	      </td>
	      <td>
	      </td>
	    </tr>
            <tr>
	      <td>
                 <a href="http://www.zib.de/tuchscherer/">Andreas Tuchscherer</a>
	      </td>
	      <td>
                 Branch-and-Price contributions
	      </td>
	      <td>
	      </td>
	    </tr> 
	</table>
</div>

