<div id="authors">

    <h2><a name="main"></a>Current main developers</h2>

        <table class="desc">
	    <tr>
	      <td width="180px">
		<a href="http://www.zib.de/berthold/">Timo Berthold</a>
	      </td>
	      <td>
		Primal heuristics, branching rules
	      </td>
	    </tr>
	    <tr>
	      <td>
		<a href="http://www.zib.de/gamrath/">Gerald Gamrath</a>
	      </td>
	      <td>
                Column generation
	      </td>
	    </tr>
	    <tr>
	      <td>
		<a href="http://www.zib.de/heinz/">Stefan Heinz</a>
	      </td>
	      <td> Solution counting, global constraints
	      </td>
	    </tr>
	    <tr>
	      <td>
		<a href="http://www.mathematik.tu-darmstadt.de/~pfetsch/index.en.html">Marc Pfetsch</a>
	      </td>
	      <td>
		Special math programming constraints, former project head
	      </td>
	      <td>
	      </td>
	    </tr>
	    <tr>
	      <td>
		<a href="http://www.math.hu-berlin.de/~stefan/">Stefan Vigerske</a>
	      </td>
	      <td>
               Mixed integer nonlinear programming
	      </td>
	    </tr>
	    <tr>
	      <td>
		<a href="http://www.zib.de/wolter/">Kati Wolter</a>
	      </td>
	      <td>
		Cutting planes, exact integer programming
	      </td>
	    </tr>
	</table>

    <h2><a name="further"></a>Further developers</h2>

    	<table class="desc">
	    <tr>
	      <td width="180px">Tobias Achterberg
	      </td>
	      <td>
		Former main developer
	      </td>
	    </tr>
	    <tr>
	      <td>
		<a href="http://www.zib.de/en/people/staff/member.html?mail=hendel">Gregor Hendel</a>
	      </td>
	      <td>
                Student assistant
              </td>
	    </tr>
            <tr>
	      <td>
		<a href="http://www.zib.de/gleixner/">Ambros Gleixner</a>
	      </td>
	      <td>
                SoPlex interface, mixed integer nonlinear programming
	      </td>
	    </tr>
	    <tr>
	      <td>
		<a href="http://www.zib.de/koch/">Thorsten Koch</a>
	      </td>
	      <td>
                Project head
	      </td>
	    </tr>
	    <tr>
	      <td>
		<a href="http://www.mso.math.uni-erlangen.de/optimization/edom/team/martin-alexander/prof-dr-alexander-martin.html">Alexander Martin</a>
	      </td>
	      <td>
		Developer of SIP &ndash; the predecessor of SCIP
	      </td>
	    </tr>
            <tr>
	      <td>
		<a href="http://www.zib.de/en/people/staff/member.html?mail=miltenberger">Matthias Miltenberger</a>
	      </td>
	      <td>
                Probing propagator
	      </td>
	    </tr>
	    <tr>
	      <td>
		Felipe Serrano
	      </td>
	      <td>
                nonlinear development
	      </td>
	    </tr>
	    <tr>
	      <td>
              Robert Waniek
	      </td>
	      <td>
                Former student assistant
              </td>
	    </tr>
	    <tr>
	      <td>
		<a href="http://www.am.uni-erlangen.de/optimization/edom/team/weninger-dieter/dieter-weninger.html">Dieter Weninger</a>
	      </td>
	      <td>
                Presolvers for independent components and dominated columns
	      </td>
	    </tr>
	    <tr>
	      <td>
		<a href="http://www.zib.de/en/people/staff/member.html?mail=michael.winkler">Michael Winkler</a>
	      </td>
	      <td>
                Student assistant
	      </td>
	    </tr>

	</table>

        <h2><a name="contributors"></a>Contributors</h2>

    	<table class="desc">
           <tr>
	      <td>
		 <a href="http://www.ifor.math.ethz.ch/~balmarti">Martin Ballerstein</a>
	      </td>
	      <td>
                 Constraint Handler for bivariate nonlinear constraints
	      </td>
	      <td>
	      </td>
	    </tr>
           <tr>
	      <td>
		 <a href="http://www.mie.utoronto.ca/faculty/beck/">Chris Beck</a>
	      </td>
	      <td>
                 Logic-based Bender's decomposition
	      </td>
	      <td>
	      </td>
	    </tr>
           <tr>
	      <td>
		 Livio Bertacco
	      </td>
	      <td>
                 Interface to <a href="http://www.fico.com/en/Products/DMTools/Pages/FICO-Xpress-Optimization-Suite.aspx">FICO/Xpress</a>
	      </td>
	    </tr>
            <tr>
	      <td>
                <a href="http://www3.math.tu-berlin.de/coga/people/bley/">Andreas Bley</a>
	      </td>
	      <td>
                 VRP example
	      </td>
	      <td>
	      </td>
	    </tr>
            <tr>
	      <td width="180px">
		<a href="http://www.dii.uchile.cl/~daespino/">Daniel Espinoza</a>
	      </td>
	      <td>
                 Interface to <a href="http://www2.isye.gatech.edu/~wcook/qsopt/">QSopt</a>
	      </td>
	      <td>
	      </td>
	    </tr>
            <tr>
	      <td>
                 John Forrest
	      </td>
	      <td>
                 Interface to <a href="http://www.coin-or.org/Clp/">CLP</a>
	      </td>
	      <td>
	      </td>
	    </tr>
            <tr>
	      <td>
                <a href="http://www.mso.math.uni-erlangen.de/optimization/edom/team/gellermann-thorsten/thorsten-gellermann.html">Thorsten Gellermann</a>
	      </td>
	      <td>
                 Generic NLP interface
	      </td>
	      <td>
	      </td>
	    </tr>
	    <tr>
	      <td>
                 Bo Jensen
	      </td>
	      <td>
                 Interface to <a href="http://www.mosek.com/">MOSEK</a>
	      </td>
	      <td>
	      </td>
	    </tr>
	    <tr>
	      <td>
                 <a href="http://www.math2.rwth-aachen.de/en/mitarbeiter/kutschka/">Manuel Kutschka</a>
	      </td>
              <td>
                 Separator for {0,1/2}-cuts
	      </td>
	    </tr>
           <tr>
	      <td>
		 <a href="http://www.ifor.math.ethz.ch/~dennism">Dennis Michaels</a>
	      </td>
	      <td>
                 Constraint Handler for bivariate nonlinear constraints
	      </td>
	      <td>
	      </td>
	    </tr>
            <tr>
	      <td>
                 Michael Perregaard
	      </td>
	      <td>
                 Interface to <a href="http://www.dashoptimization.com/home/products/products_optimizer.html">FICO/Xpress</a>
	      </td>
	    </tr>
            <tr>
	      <td>
                Fr&eacute;d&eacute;ric Pythoud
	      </td>
	      <td>
                 Superindicator constraint handler
	      </td>
	      <td>
	      </td>
	    </tr>
            <tr>
	      <td>
		<a href="http://www.zib.de/raack/">Christian Raack</a>
	      </td>
	      <td>
                 Separator for MCF cuts
	      </td>
	    </tr>
            <tr>
	      <td>
                 <a href="http://www.rambau.wm.uni-bayreuth.de/">J&ouml;rg Rambau</a>
	      </td>
	      <td>
                 Branch-and-Price contributions
	      </td>
	      <td>
	      </td>
	    </tr>
            <tr>
	      <td>
                 <a href="http://www.dei.unipd.it/~salvagni/">Domenico Salvagnin</a>
	      </td>
	      <td>
                 Feasibility Pump 2.0
	      </td>
	      <td>
	      </td>
	    </tr>
            <tr>
	      <td>
                 <a href="http://www.coga.tu-berlin.de/v-menue/mitarbeiter/jens_schulz/jens_schulz/">Jens Schulz</a>
	      </td>
	      <td>
                 Scheduling plugins: cumulative and linking constraint handler, variable bounds propagator
	      </td>
	      <td>
	      </td>
	    </tr>
            <tr>
	      <td>
                 <a href="http://www.wm.uni-bayreuth.de/index.php?id=417">Cornelius Schwarz</a>
	      </td>
	      <td>
                 Queens example
	      </td>
	      <td>
	      </td>
	    </tr>
            <tr>
	      <td>
		<a href="http://www.zib.de/en/people/staff/member.html?mail=shinano">Yuji Shinano</a>
	      </td>
	      <td>
                Parallel extension of SCIP
	      </td>
	    </tr>
            <tr>
	      <td>
		<a href="https://files.oakland.edu/users/steffy/web/">Dan Steffy</a>
	      </td>
	      <td>
                Exact integer programming
	      </td>
	    </tr>
            <tr>
	      <td>
                 <a href="http://www.zib.de/tuchscherer/">Andreas Tuchscherer</a>
	      </td>
	      <td>
                 Branch-and-Price contributions
	      </td>
	      <td>
	      </td>
	    </tr>
            <tr>
	      <td>
                Stefan Weltge
	      </td>
	      <td>
                 OBBT propagator
	      </td>
	      <td>
	      </td>
	    </tr>
	</table>
</div>

