<h3>Main developers</h3>
<table class="desc">
   <tr>
      <td class="w-200"><a href="http://www.zib.de/gamrath/">Gerald Gamrath</a></td>
      <td>Column generation, branching rules</td>
   </tr>
   <tr>
      <td><a href="http://www.zib.de/gleixner/">Ambros Gleixner</a></td>
      <td>SoPlex interface, mixed integer nonlinear programming</td>
   </tr>
   <tr>
      <td><a href="http://www.zib.de/en/people/staff/member.html?mail=hendel">Gregor Hendel</a></td>
      <td>Student assistant, primal heuristics</td>
   </tr>
   <tr>
      <td><a href="http://www.zib.de/miltenberger/">Matthias Miltenberger</a></td>
      <td>SoPlex interface, Probing propagator</td>
   </tr>
   <tr>
      <td><a href="http://www.mathematik.tu-darmstadt.de/~pfetsch/index.en.html">Marc Pfetsch</a></td>
      <td>Special math programming constraints, former project head</td>
   </tr>
   <tr>
      <td><a href="http://www.math.hu-berlin.de/~stefan/">Stefan Vigerske</a></td>
      <td>Mixed integer nonlinear programming</td>
   </tr>
   <tr>
      <td><a href="http://www.zib.de/en/people/staff/member.html?mail=michael.winkler">Michael Winkler</a></td>
      <td>Student assistant, presolving</td>
   </tr>
</table>
<h3>Further and former developers</h3>
<table class="desc">
   <tr>
      <td class="w-200"><a href="http://www.zib.de/en/people/staff/member.html?mail=achterberg">Tobias Achterberg</a></td>
      <td>Former main developer</td>
   </tr>
   <tr>
      <td><a href="http://www.zib.de/berthold/">Timo Berthold</a></td>
      <td>Former main developer, primal heuristics, branching rules</td>
   </tr>
   <tr>
      <td><a href="http://www.zib.de/heinz/">Stefan Heinz</a></td>
      <td> Former main developer, solution counting, global constraints, conflict analysis</td>
   </tr>
   <tr>
      <td><a href="http://www.zib.de/koch/">Thorsten Koch</a></td>
      <td>Project head</td>
   </tr>
   <tr>
      <td>Alexandra Kraft</td>
      <td>Former student assistant, pbm reader, Java native interface</td>
   </tr>
   <tr>
      <td><a href="http://www.am.uni-erlangen.de/?id=199">Alexander Martin</a></td>
      <td>Developer of SIP &ndash; the predecessor of SCIP</td>
   </tr>
   <tr>
      <td><a href="http://www.zib.de/en/people/staff/member.html?mail=benjamin.mueller&amp;L=1">Benjamin M&uuml;ller</a></td>
      <td>Student assistant, obbt propagator</td>
   </tr>
   <tr>
      <td><a href="http://www.zib.de/en/people/staff/member.html?mail=serrano">Felipe Serrano</a></td>
      <td>nonlinear development</td>
   </tr>
   <tr>
      <td><a href="http://www.zib.de/en/people/staff/member.html?mail=waniek&amp;L=1">Robert Waniek</a></td>
      <td>Former student assistant, odd-cycle separator, dins primal heuristic</td>
   </tr>
   <tr>
      <td><a href="http://www.mso.math.fau.de/de/wirtschaftsmathematik/team/weninger-dieter">Dieter Weninger</a></td>
      <td>Presolvers for independent components and dominated columns</td>
   </tr>
   <tr>
      <td><a href="http://www.zib.de/wolter/">Kati Wolter</a></td>
      <td>Former main developer, cutting planes, exact integer programming</td>
   </tr>
</table>

<h3 id="contributors" class="reveal">Contributors</h3>
<div style="display: block;" id="contributors_ans" class="answer">
   <table class="desc">
      <tr>
         <td class="w-200"><a href="http://www.ifor.math.ethz.ch/~balmarti">Martin Ballerstein</a></td>
         <td>Constraint Handler for bivariate nonlinear constraints</td>
      </tr>
      <tr>
         <td><a href="http://www.mie.utoronto.ca/faculty/beck/">Chris Beck</a></td>
         <td>Logic-based Bender's decomposition</td>
      </tr>
      <tr>
         <td>Livio Bertacco</td>
         <td>Interface to <a href="http://www.fico.com/en/Products/DMTools/Pages/FICO-Xpress-Optimization-Suite.aspx">FICO/Xpress</a></td>
      </tr>
      <tr>
         <td><a href="http://www3.math.tu-berlin.de/coga/people/bley/">Andreas Bley</a></td>
         <td>VRP example</td>
      </tr>
      <tr>
         <td><a href="http://www.zib.de/en/people/staff/member.html?mail=buchwald&amp;L=1">Tobias Buchwald</a></td>
         <td>Dual value heuristic</td>
      </tr>
      <tr>
         <td><a href="http://www.dii.uchile.cl/~daespino/">Daniel Espinoza</a></td>
         <td>Interface to <a href="http://www2.isye.gatech.edu/~wcook/qsopt/">QSopt</a></td>
      </tr>
      <tr>
         <td>John Forrest</td>
         <td>Interface to <a href="http://www.coin-or.org/Clp/">CLP</a></td>
      </tr>
      <tr>
         <td><a href="http://www3.mathematik.tu-darmstadt.de/hp/optimierung/gellermann-thorsten/startseite.html">Thorsten Gellermann</a></td>
         <td>Generic NLP interface</td>
      </tr>
      <tr>
         <td>Bo Jensen</td>
         <td>Interface to <a href="http://www.mosek.com/">MOSEK</a></td>
      </tr>
      <tr>
         <td><a href="http://www.math2.rwth-aachen.de/en/mitarbeiter/kutschka/">Manuel Kutschka</a></td>
         <td>Separator for {0,1/2}-cuts</td>
      </tr>
      <tr>
         <td><a href="http://www.zib.de/en/menschen/mitarbeiter/member.html?mail=maher&amp;L=0">Stephen J. Maher</a></td>
         <td>Python interface</td>
      </tr>
      <tr>
         <td><a href="http://www.ifor.math.ethz.ch/~dennism">Dennis Michaels</a></td>
         <td>Constraint Handler for bivariate nonlinear constraints</td>
      </tr>
      <tr>
         <td><a href="http://people.sutd.edu.sg/~nannicini/">Giacomo Nannicini</a></td>
         <td>GMI example</td>
      </tr>
      <tr>
         <td>Michael Perregaard</td>
         <td>Interface to <a href="http://www.fico.com/en/Products/DMTools/Pages/FICO-Xpress-Optimization-Suite.aspx">FICO/Xpress</a></td>
      </tr>
      <tr>
         <td>Fr&eacute;d&eacute;ric Pythoud</td>
         <td>Superindicator constraint handler</td>
      </tr>
      <tr>
         <td><a href="http://www.zib.de/raack/">Christian Raack</a></td>
         <td>Separator for MCF cuts</td>
      </tr>
      <tr>
         <td><a href="http://www.rambau.wm.uni-bayreuth.de/">J&ouml;rg Rambau</a></td>
         <td>Branch-and-Price contributions</td>
      </tr>
      <tr>
         <td><a href="http://www.dei.unipd.it/~salvagni/">Domenico Salvagnin</a></td>
         <td>Feasibility Pump 2.0</td>
      </tr>
      <tr>
         <td><a href="http://www.coga.tu-berlin.de/v-menue/mitarbeiter/jens_schulz/jens_schulz/">Jens Schulz</a></td>
         <td>Scheduling plugins: cumulative and linking constraint handler, variable bounds propagator</td>
      </tr>
      <tr>
         <td><a href="http://www.wm.uni-bayreuth.de/index.php?id=417">Cornelius Schwarz</a></td>
         <td>Queens example</td>
      </tr>
      <tr>
         <td><a href="http://www.zib.de/en/menschen/mitarbeiter/member.html?mail=schwarz&amp;L=0">Robert Schwarz</a></td>
         <td>Python interface</td>
      </tr>
      <tr>
         <td><a href="http://www.zib.de/en/people/staff/member.html?mail=simon&amp;L=1">Felix Simon</a></td>
         <td>Java native interface</td>
      </tr>
      <tr>
         <td><a href="http://www.zib.de/en/people/staff/member.html?mail=shinano">Yuji Shinano</a></td>
         <td>Parallel extension of SCIP</td>
      </tr>
      <tr>
         <td><a href="https://files.oakland.edu/users/steffy/web/">Dan Steffy</a></td>
         <td>Exact integer programming</td>
      </tr>
      <tr>
         <td><a href="http://www.zib.de/tuchscherer/">Andreas Tuchscherer</a></td>
         <td>Branch-and-Price contributions</td>
      </tr>
      <tr>
         <td><a href="http://www.zib.de/en/people/staff/member.html?mail=vierhaus&amp;L=1">Ingmar Vierhaus</a></td>
         <td>Nonlinear constraint parsing in CIP reader</td>
      </tr>
      <tr>
         <td><a href="http://www.math.uni-magdeburg.de/~weltge/">Stefan Weltge</a></td>
         <td>OBBT propagator</td>
      </tr>
   </table>
</div>
