/**@file   PolySCIPConfig.h
 * @brief  Some preprocessor directives
 * @author Sebastian Schenker
 *
 * defines some preprocessor directives: name of executable, current version,
 * maximal number of considered objectives; is generated by cmake
 */

#define POLYSCIP_VERSION_MAJOR 2
#define POLYSCIP_VERSION_MINOR 0
#define EXECUTABLE_NAME "polyscip"
#define POLYSCIP_MAX_NO_OBJS 30
