/**
 * @file   PolySCIPConfig.h
 * @brief  Some preprocessor directives
 * @author Sebastian Schenker
 * @attention Preprocessor directives are generated by cmake via file cmake/PolySCIPConfig.h.in
 *
 */

#define POLYSCIP_VERSION_MAJOR 2 ///< Current major version of PolySCIP
#define POLYSCIP_VERSION_MINOR 0 ///< Current minor version of PolySCIP
#define EXECUTABLE_NAME "polyscip" ///< Name of executable
#define POLYSCIP_MAX_NO_OBJS 30 ///< Maximal number of objectives considered by PolySCIP
