/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniLibraryLoader */

#ifndef _Included_de_zib_jscip_nativ_jni_JniLibraryLoader
#define _Included_de_zib_jscip_nativ_jni_JniLibraryLoader
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
