/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipBranchRelpscost */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipBranchRelpscost
#define _Included_de_zib_jscip_nativ_jni_JniScipBranchRelpscost
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipBranchRelpscost
 * Method:    includeBranchruleRelpscost
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipBranchRelpscost_includeBranchruleRelpscost
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipBranchRelpscost
 * Method:    execRelpscostBranching
 * Signature: (JZ[J[D[DI)I
 */
JNIEXPORT jint JNICALL Java_de_zib_jscip_nativ_jni_JniScipBranchRelpscost_execRelpscostBranching
  (JNIEnv *, jobject, jlong, jboolean, jlongArray, jdoubleArray, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
