/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipHeurClique */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipHeurClique
#define _Included_de_zib_jscip_nativ_jni_JniScipHeurClique
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipHeurClique
 * Method:    includeHeurClique
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipHeurClique_includeHeurClique
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
