/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipReaderCcg */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipReaderCcg
#define _Included_de_zib_jscip_nativ_jni_JniScipReaderCcg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipReaderCcg
 * Method:    includeReaderCcg
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipReaderCcg_includeReaderCcg
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipReaderCcg
 * Method:    writeCcg
 * Signature: (JJLjava/lang/String;Z[JI[JI)I
 */
JNIEXPORT jint JNICALL Java_de_zib_jscip_nativ_jni_JniScipReaderCcg_writeCcg
  (JNIEnv *, jobject, jlong, jlong, jstring, jboolean, jlongArray, jint, jlongArray, jint);

#ifdef __cplusplus
}
#endif
#endif
