/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipHeurSubnlp */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipHeurSubnlp
#define _Included_de_zib_jscip_nativ_jni_JniScipHeurSubnlp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipHeurSubnlp
 * Method:    includeHeurSubNlp
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipHeurSubnlp_includeHeurSubNlp
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipHeurSubnlp
 * Method:    updateStartpointHeurSubNlp
 * Signature: (JJJD)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipHeurSubnlp_updateStartpointHeurSubNlp
  (JNIEnv *, jobject, jlong, jlong, jlong, jdouble);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipHeurSubnlp
 * Method:    applyHeurSubNlp
 * Signature: (JJJJDD[J)I
 */
JNIEXPORT jint JNICALL Java_de_zib_jscip_nativ_jni_JniScipHeurSubnlp_applyHeurSubNlp
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jdouble, jdouble, jlongArray);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipHeurSubnlp
 * Method:    resolveSolHeurSubNlp
 * Signature: (JJJ[ZJD)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipHeurSubnlp_resolveSolHeurSubNlp
  (JNIEnv *, jobject, jlong, jlong, jlong, jbooleanArray, jlong, jdouble);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipHeurSubnlp
 * Method:    addLinearConsToNlpHeurSubNlp
 * Signature: (JJZZ)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipHeurSubnlp_addLinearConsToNlpHeurSubNlp
  (JNIEnv *, jobject, jlong, jlong, jboolean, jboolean);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipHeurSubnlp
 * Method:    getSubScipHeurSubNlp
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_de_zib_jscip_nativ_jni_JniScipHeurSubnlp_getSubScipHeurSubNlp
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipHeurSubnlp
 * Method:    getVarMappingScip2SubScipHeurSubNlp
 * Signature: (JJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_de_zib_jscip_nativ_jni_JniScipHeurSubnlp_getVarMappingScip2SubScipHeurSubNlp
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipHeurSubnlp
 * Method:    getVarMappingSubScip2ScipHeurSubNlp
 * Signature: (JJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_de_zib_jscip_nativ_jni_JniScipHeurSubnlp_getVarMappingSubScip2ScipHeurSubNlp
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipHeurSubnlp
 * Method:    getStartCandidateHeurSubNlp
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_de_zib_jscip_nativ_jni_JniScipHeurSubnlp_getStartCandidateHeurSubNlp
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
