/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipHeurRens */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipHeurRens
#define _Included_de_zib_jscip_nativ_jni_JniScipHeurRens
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipHeurRens
 * Method:    includeHeurRens
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipHeurRens_includeHeurRens
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipHeurRens
 * Method:    applyRens
 * Signature: (JJ[IDDJJCZZ)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipHeurRens_applyRens
  (JNIEnv *, jobject, jlong, jlong, jintArray, jdouble, jdouble, jlong, jlong, jchar, jboolean, jboolean);

#ifdef __cplusplus
}
#endif
#endif
