/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipReaderMps */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipReaderMps
#define _Included_de_zib_jscip_nativ_jni_JniScipReaderMps
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipReaderMps
 * Method:    includeReaderMps
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipReaderMps_includeReaderMps
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
