/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipReaderLp */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipReaderLp
#define _Included_de_zib_jscip_nativ_jni_JniScipReaderLp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipReaderLp
 * Method:    includeReaderLp
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipReaderLp_includeReaderLp
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipReaderLp
 * Method:    readLp
 * Signature: (JJLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_de_zib_jscip_nativ_jni_JniScipReaderLp_readLp
  (JNIEnv *, jobject, jlong, jlong, jstring);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipReaderLp
 * Method:    writeLp
 * Signature: (JJLjava/lang/String;ZIDD[JIIIII[JI)I
 */
JNIEXPORT jint JNICALL Java_de_zib_jscip_nativ_jni_JniScipReaderLp_writeLp
  (JNIEnv *, jobject, jlong, jlong, jstring, jboolean, jint, jdouble, jdouble, jlongArray, jint, jint, jint, jint, jint, jlongArray, jint);

#ifdef __cplusplus
}
#endif
#endif
