/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipReaderSol */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipReaderSol
#define _Included_de_zib_jscip_nativ_jni_JniScipReaderSol
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipReaderSol
 * Method:    includeReaderSol
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipReaderSol_includeReaderSol
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
