/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipConsLogicor */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipConsLogicor
#define _Included_de_zib_jscip_nativ_jni_JniScipConsLogicor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsLogicor
 * Method:    includeConshdlrLogicor
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsLogicor_includeConshdlrLogicor
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsLogicor
 * Method:    createConsLogicor
 * Signature: (JLjava/lang/String;I[JZZZZZZZZZZ)J
 */
JNIEXPORT jlong JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsLogicor_createConsLogicor
  (JNIEnv *, jobject, jlong, jstring, jint, jlongArray, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsLogicor
 * Method:    createConsBasicLogicor
 * Signature: (JLjava/lang/String;I[J)J
 */
JNIEXPORT jlong JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsLogicor_createConsBasicLogicor
  (JNIEnv *, jobject, jlong, jstring, jint, jlongArray);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsLogicor
 * Method:    addCoefLogicor
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsLogicor_addCoefLogicor
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsLogicor
 * Method:    getNVarsLogicor
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsLogicor_getNVarsLogicor
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsLogicor
 * Method:    getVarsLogicor
 * Signature: (JJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsLogicor_getVarsLogicor
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsLogicor
 * Method:    getDualsolLogicor
 * Signature: (JJ)D
 */
JNIEXPORT jdouble JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsLogicor_getDualsolLogicor
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsLogicor
 * Method:    getDualfarkasLogicor
 * Signature: (JJ)D
 */
JNIEXPORT jdouble JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsLogicor_getDualfarkasLogicor
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsLogicor
 * Method:    getRowLogicor
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsLogicor_getRowLogicor
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
