/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipPresolImplics */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipPresolImplics
#define _Included_de_zib_jscip_nativ_jni_JniScipPresolImplics
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipPresolImplics
 * Method:    includePresolImplics
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipPresolImplics_includePresolImplics
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
