/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipBranchFullstrong */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipBranchFullstrong
#define _Included_de_zib_jscip_nativ_jni_JniScipBranchFullstrong
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipBranchFullstrong
 * Method:    includeBranchruleFullstrong
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipBranchFullstrong_includeBranchruleFullstrong
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipBranchFullstrong
 * Method:    selectVarStrongBranching
 * Signature: (J[J[D[D[Z[ZIII[IZ[I[D[D[D[Z[Z[D[I)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipBranchFullstrong_selectVarStrongBranching
  (JNIEnv *, jobject, jlong, jlongArray, jdoubleArray, jdoubleArray, jbooleanArray, jbooleanArray, jint, jint, jint, jintArray, jboolean, jintArray, jdoubleArray, jdoubleArray, jdoubleArray, jbooleanArray, jbooleanArray, jdoubleArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
