/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipHeurLinesearchdiving */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipHeurLinesearchdiving
#define _Included_de_zib_jscip_nativ_jni_JniScipHeurLinesearchdiving
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipHeurLinesearchdiving
 * Method:    includeHeurLinesearchdiving
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipHeurLinesearchdiving_includeHeurLinesearchdiving
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
