/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipBranchInference */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipBranchInference
#define _Included_de_zib_jscip_nativ_jni_JniScipBranchInference
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipBranchInference
 * Method:    includeBranchruleInference
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipBranchInference_includeBranchruleInference
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
