/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipHeurNlpdiving */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipHeurNlpdiving
#define _Included_de_zib_jscip_nativ_jni_JniScipHeurNlpdiving
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipHeurNlpdiving
 * Method:    includeHeurNlpdiving
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipHeurNlpdiving_includeHeurNlpdiving
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
