/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipPresolBoundshift */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipPresolBoundshift
#define _Included_de_zib_jscip_nativ_jni_JniScipPresolBoundshift
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipPresolBoundshift
 * Method:    includePresolBoundshift
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipPresolBoundshift_includePresolBoundshift
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
