/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipConsConjunction */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipConsConjunction
#define _Included_de_zib_jscip_nativ_jni_JniScipConsConjunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsConjunction
 * Method:    includeConshdlrConjunction
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsConjunction_includeConshdlrConjunction
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsConjunction
 * Method:    createConsConjunction
 * Signature: (JLjava/lang/String;I[JZZZZZ)J
 */
JNIEXPORT jlong JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsConjunction_createConsConjunction
  (JNIEnv *, jobject, jlong, jstring, jint, jlongArray, jboolean, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsConjunction
 * Method:    createConsBasicConjunction
 * Signature: (JLjava/lang/String;I[J)J
 */
JNIEXPORT jlong JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsConjunction_createConsBasicConjunction
  (JNIEnv *, jobject, jlong, jstring, jint, jlongArray);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsConjunction
 * Method:    addConsElemConjunction
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsConjunction_addConsElemConjunction
  (JNIEnv *, jobject, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
