/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipHeurZirounding */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipHeurZirounding
#define _Included_de_zib_jscip_nativ_jni_JniScipHeurZirounding
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipHeurZirounding
 * Method:    includeHeurZirounding
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipHeurZirounding_includeHeurZirounding
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
