/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipDialogDefault */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipDialogDefault
#define _Included_de_zib_jscip_nativ_jni_JniScipDialogDefault
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipDialogDefault
 * Method:    createRootDialog
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_zib_jscip_nativ_jni_JniScipDialogDefault_createRootDialog
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipDialogDefault
 * Method:    includeDialogDefault
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipDialogDefault_includeDialogDefault
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipDialogDefault
 * Method:    includeDialogDefaultSet
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipDialogDefault_includeDialogDefaultSet
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipDialogDefault
 * Method:    includeDialogDefaultFix
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipDialogDefault_includeDialogDefaultFix
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
