/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipConsSoc */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipConsSoc
#define _Included_de_zib_jscip_nativ_jni_JniScipConsSoc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsSoc
 * Method:    includeConshdlrSOC
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsSoc_includeConshdlrSOC
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsSoc
 * Method:    createConsSOC
 * Signature: (JLjava/lang/String;I[J[D[DDJDDZZZZZZZZZ)J
 */
JNIEXPORT jlong JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsSoc_createConsSOC
  (JNIEnv *, jobject, jlong, jstring, jint, jlongArray, jdoubleArray, jdoubleArray, jdouble, jlong, jdouble, jdouble, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsSoc
 * Method:    createConsBasicSOC
 * Signature: (JLjava/lang/String;I[J[D[DDJDD)J
 */
JNIEXPORT jlong JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsSoc_createConsBasicSOC
  (JNIEnv *, jobject, jlong, jstring, jint, jlongArray, jdoubleArray, jdoubleArray, jdouble, jlong, jdouble, jdouble);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsSoc
 * Method:    getNlRowSOC
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsSoc_getNlRowSOC
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsSoc
 * Method:    getNLhsVarsSOC
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsSoc_getNLhsVarsSOC
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsSoc
 * Method:    getLhsVarsSOC
 * Signature: (JJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsSoc_getLhsVarsSOC
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsSoc
 * Method:    getLhsCoefsSOC
 * Signature: (JJ)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsSoc_getLhsCoefsSOC
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsSoc
 * Method:    getLhsOffsetsSOC
 * Signature: (JJ)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsSoc_getLhsOffsetsSOC
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsSoc
 * Method:    getLhsConstantSOC
 * Signature: (JJ)D
 */
JNIEXPORT jdouble JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsSoc_getLhsConstantSOC
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsSoc
 * Method:    getRhsVarSOC
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsSoc_getRhsVarSOC
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsSoc
 * Method:    getRhsCoefSOC
 * Signature: (JJ)D
 */
JNIEXPORT jdouble JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsSoc_getRhsCoefSOC
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsSoc
 * Method:    getRhsOffsetSOC
 * Signature: (JJ)D
 */
JNIEXPORT jdouble JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsSoc_getRhsOffsetSOC
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsSoc
 * Method:    addToNlpiProblemSOC
 * Signature: (JJJJJZ)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsSoc_addToNlpiProblemSOC
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
