/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipBranchPscost */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipBranchPscost
#define _Included_de_zib_jscip_nativ_jni_JniScipBranchPscost
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipBranchPscost
 * Method:    includeBranchrulePscost
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipBranchPscost_includeBranchrulePscost
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
