/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipReaderFix */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipReaderFix
#define _Included_de_zib_jscip_nativ_jni_JniScipReaderFix
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipReaderFix
 * Method:    includeReaderFix
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipReaderFix_includeReaderFix
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
