/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipDisp */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipDisp
#define _Included_de_zib_jscip_nativ_jni_JniScipDisp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipDisp
 * Method:    dispGetData
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_zib_jscip_nativ_jni_JniScipDisp_dispGetData
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipDisp
 * Method:    dispSetData
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipDisp_dispSetData
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipDisp
 * Method:    dispGetName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_zib_jscip_nativ_jni_JniScipDisp_dispGetName
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipDisp
 * Method:    dispGetDesc
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_zib_jscip_nativ_jni_JniScipDisp_dispGetDesc
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipDisp
 * Method:    dispGetHeader
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_zib_jscip_nativ_jni_JniScipDisp_dispGetHeader
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipDisp
 * Method:    dispGetWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_zib_jscip_nativ_jni_JniScipDisp_dispGetWidth
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipDisp
 * Method:    dispGetPriority
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_zib_jscip_nativ_jni_JniScipDisp_dispGetPriority
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipDisp
 * Method:    dispGetPosition
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_zib_jscip_nativ_jni_JniScipDisp_dispGetPosition
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipDisp
 * Method:    dispGetStatus
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_zib_jscip_nativ_jni_JniScipDisp_dispGetStatus
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipDisp
 * Method:    dispIsInitialized
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_de_zib_jscip_nativ_jni_JniScipDisp_dispIsInitialized
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipDisp
 * Method:    dispLongint
 * Signature: (JJJI)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipDisp_dispLongint
  (JNIEnv *, jobject, jlong, jlong, jlong, jint);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipDisp
 * Method:    dispInt
 * Signature: (JJII)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipDisp_dispInt
  (JNIEnv *, jobject, jlong, jlong, jint, jint);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipDisp
 * Method:    dispTime
 * Signature: (JJDI)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipDisp_dispTime
  (JNIEnv *, jobject, jlong, jlong, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
