/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipReaderPip */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipReaderPip
#define _Included_de_zib_jscip_nativ_jni_JniScipReaderPip
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipReaderPip
 * Method:    includeReaderPip
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipReaderPip_includeReaderPip
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipReaderPip
 * Method:    readPip
 * Signature: (JJLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_de_zib_jscip_nativ_jni_JniScipReaderPip_readPip
  (JNIEnv *, jobject, jlong, jlong, jstring);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipReaderPip
 * Method:    writePip
 * Signature: (JJLjava/lang/String;ZIDD[JIIIII[JI)I
 */
JNIEXPORT jint JNICALL Java_de_zib_jscip_nativ_jni_JniScipReaderPip_writePip
  (JNIEnv *, jobject, jlong, jlong, jstring, jboolean, jint, jdouble, jdouble, jlongArray, jint, jint, jint, jint, jint, jlongArray, jint);

#ifdef __cplusplus
}
#endif
#endif
