/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipSepaRapidlearning */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipSepaRapidlearning
#define _Included_de_zib_jscip_nativ_jni_JniScipSepaRapidlearning
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipSepaRapidlearning
 * Method:    includeSepaRapidlearning
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipSepaRapidlearning_includeSepaRapidlearning
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
