/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipHeurRootsoldiving */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipHeurRootsoldiving
#define _Included_de_zib_jscip_nativ_jni_JniScipHeurRootsoldiving
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipHeurRootsoldiving
 * Method:    includeHeurRootsoldiving
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipHeurRootsoldiving_includeHeurRootsoldiving
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
