/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipPresolTrivial */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipPresolTrivial
#define _Included_de_zib_jscip_nativ_jni_JniScipPresolTrivial
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipPresolTrivial
 * Method:    includePresolTrivial
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipPresolTrivial_includePresolTrivial
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
