/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipReaderGms */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipReaderGms
#define _Included_de_zib_jscip_nativ_jni_JniScipReaderGms
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipReaderGms
 * Method:    includeReaderGms
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipReaderGms_includeReaderGms
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipReaderGms
 * Method:    writeGms
 * Signature: (JJLjava/lang/String;ZIDD[JIIIII[JI)I
 */
JNIEXPORT jint JNICALL Java_de_zib_jscip_nativ_jni_JniScipReaderGms_writeGms
  (JNIEnv *, jobject, jlong, jlong, jstring, jboolean, jint, jdouble, jdouble, jlongArray, jint, jint, jint, jint, jint, jlongArray, jint);

#ifdef __cplusplus
}
#endif
#endif
