/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipConsLinking */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipConsLinking
#define _Included_de_zib_jscip_nativ_jni_JniScipConsLinking
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsLinking
 * Method:    includeConshdlrLinking
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsLinking_includeConshdlrLinking
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsLinking
 * Method:    createConsLinking
 * Signature: (JLjava/lang/String;J[J[IIZZZZZZZZZZ)J
 */
JNIEXPORT jlong JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsLinking_createConsLinking
  (JNIEnv *, jobject, jlong, jstring, jlong, jlongArray, jintArray, jint, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsLinking
 * Method:    createConsBasicLinking
 * Signature: (JLjava/lang/String;J[J[II)J
 */
JNIEXPORT jlong JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsLinking_createConsBasicLinking
  (JNIEnv *, jobject, jlong, jstring, jlong, jlongArray, jintArray, jint);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsLinking
 * Method:    existsConsLinking
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsLinking_existsConsLinking
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsLinking
 * Method:    getConsLinking
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsLinking_getConsLinking
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsLinking
 * Method:    getIntvarLinking
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsLinking_getIntvarLinking
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsLinking
 * Method:    getNBinvarsLinking
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsLinking_getNBinvarsLinking
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsLinking
 * Method:    getValsLinking
 * Signature: (JJ)[I
 */
JNIEXPORT jintArray JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsLinking_getValsLinking
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
