/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipHeurRounding */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipHeurRounding
#define _Included_de_zib_jscip_nativ_jni_JniScipHeurRounding
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipHeurRounding
 * Method:    includeHeurRounding
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipHeurRounding_includeHeurRounding
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
