/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipReaderCip */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipReaderCip
#define _Included_de_zib_jscip_nativ_jni_JniScipReaderCip
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipReaderCip
 * Method:    includeReaderCip
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipReaderCip_includeReaderCip
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
