/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipBranchLeastinf */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipBranchLeastinf
#define _Included_de_zib_jscip_nativ_jni_JniScipBranchLeastinf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipBranchLeastinf
 * Method:    includeBranchruleLeastinf
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipBranchLeastinf_includeBranchruleLeastinf
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
