/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipBranchAllfullstrong */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipBranchAllfullstrong
#define _Included_de_zib_jscip_nativ_jni_JniScipBranchAllfullstrong
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipBranchAllfullstrong
 * Method:    selectVarPseudoStrongBranching
 * Signature: (J[J[Z[ZIIZ[I[D[D[D[Z[Z[D[I)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipBranchAllfullstrong_selectVarPseudoStrongBranching
  (JNIEnv *, jobject, jlong, jlongArray, jbooleanArray, jbooleanArray, jint, jint, jboolean, jintArray, jdoubleArray, jdoubleArray, jdoubleArray, jbooleanArray, jbooleanArray, jdoubleArray, jintArray);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipBranchAllfullstrong
 * Method:    includeBranchruleAllfullstrong
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipBranchAllfullstrong_includeBranchruleAllfullstrong
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
