/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipHeurShifting */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipHeurShifting
#define _Included_de_zib_jscip_nativ_jni_JniScipHeurShifting
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipHeurShifting
 * Method:    includeHeurShifting
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipHeurShifting_includeHeurShifting
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
