/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipHeurSimplerounding */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipHeurSimplerounding
#define _Included_de_zib_jscip_nativ_jni_JniScipHeurSimplerounding
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipHeurSimplerounding
 * Method:    includeHeurSimplerounding
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipHeurSimplerounding_includeHeurSimplerounding
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
