/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipPresolInttobinary */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipPresolInttobinary
#define _Included_de_zib_jscip_nativ_jni_JniScipPresolInttobinary
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipPresolInttobinary
 * Method:    includePresolInttobinary
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipPresolInttobinary_includePresolInttobinary
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
