/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipDispDefault */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipDispDefault
#define _Included_de_zib_jscip_nativ_jni_JniScipDispDefault
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipDispDefault
 * Method:    includeDispDefault
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipDispDefault_includeDispDefault
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
