/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipSepaImpliedbounds */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipSepaImpliedbounds
#define _Included_de_zib_jscip_nativ_jni_JniScipSepaImpliedbounds
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipSepaImpliedbounds
 * Method:    includeSepaImpliedbounds
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipSepaImpliedbounds_includeSepaImpliedbounds
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
