/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipReaderOpb */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipReaderOpb
#define _Included_de_zib_jscip_nativ_jni_JniScipReaderOpb
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipReaderOpb
 * Method:    includeReaderOpb
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipReaderOpb_includeReaderOpb
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipReaderOpb
 * Method:    readOpb
 * Signature: (JJLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_de_zib_jscip_nativ_jni_JniScipReaderOpb_readOpb
  (JNIEnv *, jobject, jlong, jlong, jstring);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipReaderOpb
 * Method:    writeOpb
 * Signature: (JJLjava/lang/String;ZIDD[JIIIII[JI[JIZ)I
 */
JNIEXPORT jint JNICALL Java_de_zib_jscip_nativ_jni_JniScipReaderOpb_writeOpb
  (JNIEnv *, jobject, jlong, jlong, jstring, jboolean, jint, jdouble, jdouble, jlongArray, jint, jint, jint, jint, jint, jlongArray, jint, jlongArray, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
