/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipHeurPscostdiving */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipHeurPscostdiving
#define _Included_de_zib_jscip_nativ_jni_JniScipHeurPscostdiving
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipHeurPscostdiving
 * Method:    includeHeurPscostdiving
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipHeurPscostdiving_includeHeurPscostdiving
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
