/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipImplics */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipImplics
#define _Included_de_zib_jscip_nativ_jni_JniScipImplics
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipImplics
 * Method:    cliqueSearchVar
 * Signature: (JJZ)I
 */
JNIEXPORT jint JNICALL Java_de_zib_jscip_nativ_jni_JniScipImplics_cliqueSearchVar
  (JNIEnv *, jobject, jlong, jlong, jboolean);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipImplics
 * Method:    cliqueHasVar
 * Signature: (JJZ)Z
 */
JNIEXPORT jboolean JNICALL Java_de_zib_jscip_nativ_jni_JniScipImplics_cliqueHasVar
  (JNIEnv *, jobject, jlong, jlong, jboolean);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipImplics
 * Method:    cliqueGetNVars
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_zib_jscip_nativ_jni_JniScipImplics_cliqueGetNVars
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipImplics
 * Method:    cliqueGetVars
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_de_zib_jscip_nativ_jni_JniScipImplics_cliqueGetVars
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipImplics
 * Method:    cliqueGetValues
 * Signature: (J)[Z
 */
JNIEXPORT jbooleanArray JNICALL Java_de_zib_jscip_nativ_jni_JniScipImplics_cliqueGetValues
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipImplics
 * Method:    cliqueGetId
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_zib_jscip_nativ_jni_JniScipImplics_cliqueGetId
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
