/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipConsCountsols */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipConsCountsols
#define _Included_de_zib_jscip_nativ_jni_JniScipConsCountsols
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsCountsols
 * Method:    includeConshdlrCountsols
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsCountsols_includeConshdlrCountsols
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsCountsols
 * Method:    count
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsCountsols_count
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsCountsols
 * Method:    getNCountedFeasSubtrees
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsCountsols_getNCountedFeasSubtrees
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsCountsols
 * Method:    setParamsCountsols
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsCountsols_setParamsCountsols
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
