/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipNodeselBfs */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipNodeselBfs
#define _Included_de_zib_jscip_nativ_jni_JniScipNodeselBfs
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipNodeselBfs
 * Method:    includeNodeselBfs
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipNodeselBfs_includeNodeselBfs
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
