/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipHeurFracdiving */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipHeurFracdiving
#define _Included_de_zib_jscip_nativ_jni_JniScipHeurFracdiving
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipHeurFracdiving
 * Method:    includeHeurFracdiving
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipHeurFracdiving_includeHeurFracdiving
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
