/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipReaderOsil */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipReaderOsil
#define _Included_de_zib_jscip_nativ_jni_JniScipReaderOsil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipReaderOsil
 * Method:    includeReaderOsil
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipReaderOsil_includeReaderOsil
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
