/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipReaderPpm */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipReaderPpm
#define _Included_de_zib_jscip_nativ_jni_JniScipReaderPpm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipReaderPpm
 * Method:    includeReaderPpm
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipReaderPpm_includeReaderPpm
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipReaderPpm
 * Method:    writePpm
 * Signature: (JJLjava/lang/String;JZ[JI[JI)I
 */
JNIEXPORT jint JNICALL Java_de_zib_jscip_nativ_jni_JniScipReaderPpm_writePpm
  (JNIEnv *, jobject, jlong, jlong, jstring, jlong, jboolean, jlongArray, jint, jlongArray, jint);

#ifdef __cplusplus
}
#endif
#endif
