/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipCutpool */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipCutpool
#define _Included_de_zib_jscip_nativ_jni_JniScipCutpool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipCutpool
 * Method:    cutGetRow
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_zib_jscip_nativ_jni_JniScipCutpool_cutGetRow
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipCutpool
 * Method:    cutGetAge
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_zib_jscip_nativ_jni_JniScipCutpool_cutGetAge
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipCutpool
 * Method:    cutpoolGetCuts
 * Signature: (J)[J
 */
JNIEXPORT jlongArray JNICALL Java_de_zib_jscip_nativ_jni_JniScipCutpool_cutpoolGetCuts
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipCutpool
 * Method:    cutpoolGetNCuts
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_zib_jscip_nativ_jni_JniScipCutpool_cutpoolGetNCuts
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipCutpool
 * Method:    cutpoolGetMaxNCuts
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_zib_jscip_nativ_jni_JniScipCutpool_cutpoolGetMaxNCuts
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipCutpool
 * Method:    cutpoolGetTime
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_de_zib_jscip_nativ_jni_JniScipCutpool_cutpoolGetTime
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipCutpool
 * Method:    cutpoolGetNCalls
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_zib_jscip_nativ_jni_JniScipCutpool_cutpoolGetNCalls
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipCutpool
 * Method:    cutpoolGetNCutsFound
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_zib_jscip_nativ_jni_JniScipCutpool_cutpoolGetNCutsFound
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
