/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipHeurMutation */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipHeurMutation
#define _Included_de_zib_jscip_nativ_jni_JniScipHeurMutation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipHeurMutation
 * Method:    includeHeurMutation
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipHeurMutation_includeHeurMutation
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
