/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipSepaOddcycle */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipSepaOddcycle
#define _Included_de_zib_jscip_nativ_jni_JniScipSepaOddcycle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipSepaOddcycle
 * Method:    includeSepaOddcycle
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipSepaOddcycle_includeSepaOddcycle
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
