/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipPropRootredcost */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipPropRootredcost
#define _Included_de_zib_jscip_nativ_jni_JniScipPropRootredcost
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipPropRootredcost
 * Method:    includePropRootredcost
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipPropRootredcost_includePropRootredcost
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
