/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipVartype */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipVartype
#define _Included_de_zib_jscip_nativ_jni_JniScipVartype
#ifdef __cplusplus
extern "C" {
#endif
#undef de_zib_jscip_nativ_jni_JniScipVartype_SCIP_VARTYPE_BINARY
#define de_zib_jscip_nativ_jni_JniScipVartype_SCIP_VARTYPE_BINARY 0L
#undef de_zib_jscip_nativ_jni_JniScipVartype_SCIP_VARTYPE_INTEGER
#define de_zib_jscip_nativ_jni_JniScipVartype_SCIP_VARTYPE_INTEGER 1L
#undef de_zib_jscip_nativ_jni_JniScipVartype_SCIP_VARTYPE_IMPLINT
#define de_zib_jscip_nativ_jni_JniScipVartype_SCIP_VARTYPE_IMPLINT 2L
#undef de_zib_jscip_nativ_jni_JniScipVartype_SCIP_VARTYPE_CONTINUOUS
#define de_zib_jscip_nativ_jni_JniScipVartype_SCIP_VARTYPE_CONTINUOUS 3L
#ifdef __cplusplus
}
#endif
#endif
