/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipConsKnapsack */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipConsKnapsack
#define _Included_de_zib_jscip_nativ_jni_JniScipConsKnapsack
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsKnapsack
 * Method:    includeConshdlrKnapsack
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsKnapsack_includeConshdlrKnapsack
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsKnapsack
 * Method:    createConsKnapsack
 * Signature: (JLjava/lang/String;I[J[JJZZZZZZZZZZ)J
 */
JNIEXPORT jlong JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsKnapsack_createConsKnapsack
  (JNIEnv *, jobject, jlong, jstring, jint, jlongArray, jlongArray, jlong, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsKnapsack
 * Method:    createConsBasicKnapsack
 * Signature: (JLjava/lang/String;I[J[JJ)J
 */
JNIEXPORT jlong JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsKnapsack_createConsBasicKnapsack
  (JNIEnv *, jobject, jlong, jstring, jint, jlongArray, jlongArray, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsKnapsack
 * Method:    addCoefKnapsack
 * Signature: (JJJJ)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsKnapsack_addCoefKnapsack
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsKnapsack
 * Method:    getCapacityKnapsack
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsKnapsack_getCapacityKnapsack
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsKnapsack
 * Method:    chgCapacityKnapsack
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsKnapsack_chgCapacityKnapsack
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsKnapsack
 * Method:    getNVarsKnapsack
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsKnapsack_getNVarsKnapsack
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsKnapsack
 * Method:    getVarsKnapsack
 * Signature: (JJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsKnapsack_getVarsKnapsack
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsKnapsack
 * Method:    getWeightsKnapsack
 * Signature: (JJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsKnapsack_getWeightsKnapsack
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsKnapsack
 * Method:    getDualsolKnapsack
 * Signature: (JJ)D
 */
JNIEXPORT jdouble JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsKnapsack_getDualsolKnapsack
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsKnapsack
 * Method:    getDualfarkasKnapsack
 * Signature: (JJ)D
 */
JNIEXPORT jdouble JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsKnapsack_getDualfarkasKnapsack
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsKnapsack
 * Method:    getRowKnapsack
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsKnapsack_getRowKnapsack
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
