/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipHeurLocalbranching */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipHeurLocalbranching
#define _Included_de_zib_jscip_nativ_jni_JniScipHeurLocalbranching
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipHeurLocalbranching
 * Method:    includeHeurLocalbranching
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipHeurLocalbranching_includeHeurLocalbranching
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
