/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipPropPseudoobj */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipPropPseudoobj
#define _Included_de_zib_jscip_nativ_jni_JniScipPropPseudoobj
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipPropPseudoobj
 * Method:    includePropPseudoobj
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipPropPseudoobj_includePropPseudoobj
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipPropPseudoobj
 * Method:    propagateCutoffboundVar
 * Signature: (JJJDD)Z
 */
JNIEXPORT jboolean JNICALL Java_de_zib_jscip_nativ_jni_JniScipPropPseudoobj_propagateCutoffboundVar
  (JNIEnv *, jobject, jlong, jlong, jlong, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
