/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipTree */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipTree
#define _Included_de_zib_jscip_nativ_jni_JniScipTree
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipTree
 * Method:    nodeGetParentBranchings
 * Signature: (J[J[D[I[II)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipTree_nodeGetParentBranchings
  (JNIEnv *, jobject, jlong, jlongArray, jdoubleArray, jintArray, jintArray, jint);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipTree
 * Method:    nodeGetAncestorBranchings
 * Signature: (J[J[D[I[II)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipTree_nodeGetAncestorBranchings
  (JNIEnv *, jobject, jlong, jlongArray, jdoubleArray, jintArray, jintArray, jint);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipTree
 * Method:    nodePrintAncestorBranchings
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipTree_nodePrintAncestorBranchings
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipTree
 * Method:    nodeGetAncestorBranchingPath
 * Signature: (J[J[D[I[II[I[II)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipTree_nodeGetAncestorBranchingPath
  (JNIEnv *, jobject, jlong, jlongArray, jdoubleArray, jintArray, jintArray, jint, jintArray, jintArray, jint);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipTree
 * Method:    nodesSharePath
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_de_zib_jscip_nativ_jni_JniScipTree_nodesSharePath
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipTree
 * Method:    nodesGetCommonAncestor
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_de_zib_jscip_nativ_jni_JniScipTree_nodesGetCommonAncestor
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipTree
 * Method:    nodeGetType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_zib_jscip_nativ_jni_JniScipTree_nodeGetType
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipTree
 * Method:    nodeGetNumber
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_zib_jscip_nativ_jni_JniScipTree_nodeGetNumber
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipTree
 * Method:    nodeGetDepth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_de_zib_jscip_nativ_jni_JniScipTree_nodeGetDepth
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipTree
 * Method:    nodeGetLowerbound
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_de_zib_jscip_nativ_jni_JniScipTree_nodeGetLowerbound
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipTree
 * Method:    nodeGetEstimate
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_de_zib_jscip_nativ_jni_JniScipTree_nodeGetEstimate
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipTree
 * Method:    nodeGetDomchg
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_zib_jscip_nativ_jni_JniScipTree_nodeGetDomchg
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipTree
 * Method:    nodeGetParent
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_zib_jscip_nativ_jni_JniScipTree_nodeGetParent
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipTree
 * Method:    nodeIsActive
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_de_zib_jscip_nativ_jni_JniScipTree_nodeIsActive
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipTree
 * Method:    nodeIsPropagatedAgain
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_de_zib_jscip_nativ_jni_JniScipTree_nodeIsPropagatedAgain
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
