/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipHeurUndercover */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipHeurUndercover
#define _Included_de_zib_jscip_nativ_jni_JniScipHeurUndercover
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipHeurUndercover
 * Method:    includeHeurUndercover
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipHeurUndercover_includeHeurUndercover
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipHeurUndercover
 * Method:    computeCoverUndercover
 * Signature: (J[IDDDZZZC[Z)J
 */
JNIEXPORT jlong JNICALL Java_de_zib_jscip_nativ_jni_JniScipHeurUndercover_computeCoverUndercover
  (JNIEnv *, jobject, jlong, jintArray, jdouble, jdouble, jdouble, jboolean, jboolean, jboolean, jchar, jbooleanArray);

#ifdef __cplusplus
}
#endif
#endif
