/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipConsSos2 */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipConsSos2
#define _Included_de_zib_jscip_nativ_jni_JniScipConsSos2
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsSos2
 * Method:    includeConshdlrSOS2
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsSos2_includeConshdlrSOS2
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsSos2
 * Method:    createConsSOS2
 * Signature: (JLjava/lang/String;I[J[DZZZZZZZZZ)J
 */
JNIEXPORT jlong JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsSos2_createConsSOS2
  (JNIEnv *, jobject, jlong, jstring, jint, jlongArray, jdoubleArray, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsSos2
 * Method:    createConsBasicSOS2
 * Signature: (JLjava/lang/String;I[J[D)J
 */
JNIEXPORT jlong JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsSos2_createConsBasicSOS2
  (JNIEnv *, jobject, jlong, jstring, jint, jlongArray, jdoubleArray);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsSos2
 * Method:    addVarSOS2
 * Signature: (JJJD)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsSos2_addVarSOS2
  (JNIEnv *, jobject, jlong, jlong, jlong, jdouble);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsSos2
 * Method:    appendVarSOS2
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsSos2_appendVarSOS2
  (JNIEnv *, jobject, jlong, jlong, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsSos2
 * Method:    getNVarsSOS2
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsSos2_getNVarsSOS2
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsSos2
 * Method:    getVarsSOS2
 * Signature: (JJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsSos2_getVarsSOS2
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsSos2
 * Method:    getWeightsSOS2
 * Signature: (JJ)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsSos2_getWeightsSOS2
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
