/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipReaderZpl */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipReaderZpl
#define _Included_de_zib_jscip_nativ_jni_JniScipReaderZpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipReaderZpl
 * Method:    includeReaderZpl
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipReaderZpl_includeReaderZpl
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
