/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipConsVarbound */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipConsVarbound
#define _Included_de_zib_jscip_nativ_jni_JniScipConsVarbound
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsVarbound
 * Method:    includeConshdlrVarbound
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsVarbound_includeConshdlrVarbound
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsVarbound
 * Method:    createConsVarbound
 * Signature: (JLjava/lang/String;JJDDDZZZZZZZZZZ)J
 */
JNIEXPORT jlong JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsVarbound_createConsVarbound
  (JNIEnv *, jobject, jlong, jstring, jlong, jlong, jdouble, jdouble, jdouble, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsVarbound
 * Method:    createConsBasicVarbound
 * Signature: (JLjava/lang/String;JJDDD)J
 */
JNIEXPORT jlong JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsVarbound_createConsBasicVarbound
  (JNIEnv *, jobject, jlong, jstring, jlong, jlong, jdouble, jdouble, jdouble);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsVarbound
 * Method:    getLhsVarbound
 * Signature: (JJ)D
 */
JNIEXPORT jdouble JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsVarbound_getLhsVarbound
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsVarbound
 * Method:    getRhsVarbound
 * Signature: (JJ)D
 */
JNIEXPORT jdouble JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsVarbound_getRhsVarbound
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsVarbound
 * Method:    getVarVarbound
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsVarbound_getVarVarbound
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsVarbound
 * Method:    getVbdvarVarbound
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsVarbound_getVbdvarVarbound
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsVarbound
 * Method:    getVbdcoefVarbound
 * Signature: (JJ)D
 */
JNIEXPORT jdouble JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsVarbound_getVbdcoefVarbound
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsVarbound
 * Method:    getDualsolVarbound
 * Signature: (JJ)D
 */
JNIEXPORT jdouble JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsVarbound_getDualsolVarbound
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsVarbound
 * Method:    getDualfarkasVarbound
 * Signature: (JJ)D
 */
JNIEXPORT jdouble JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsVarbound_getDualfarkasVarbound
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsVarbound
 * Method:    getRowVarbound
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsVarbound_getRowVarbound
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
