/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipSepaZerohalf */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipSepaZerohalf
#define _Included_de_zib_jscip_nativ_jni_JniScipSepaZerohalf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipSepaZerohalf
 * Method:    includeSepaZerohalf
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipSepaZerohalf_includeSepaZerohalf
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
