/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipBoundtype */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipBoundtype
#define _Included_de_zib_jscip_nativ_jni_JniScipBoundtype
#ifdef __cplusplus
extern "C" {
#endif
#undef de_zib_jscip_nativ_jni_JniScipBoundtype_SCIP_BOUNDTYPE_LOWER
#define de_zib_jscip_nativ_jni_JniScipBoundtype_SCIP_BOUNDTYPE_LOWER 0L
#undef de_zib_jscip_nativ_jni_JniScipBoundtype_SCIP_BOUNDTYPE_UPPER
#define de_zib_jscip_nativ_jni_JniScipBoundtype_SCIP_BOUNDTYPE_UPPER 1L
#ifdef __cplusplus
}
#endif
#endif
