/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipConsSuperindicator */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipConsSuperindicator
#define _Included_de_zib_jscip_nativ_jni_JniScipConsSuperindicator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsSuperindicator
 * Method:    includeConshdlrSuperindicator
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsSuperindicator_includeConshdlrSuperindicator
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsSuperindicator
 * Method:    getBinaryVarSuperindicator
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsSuperindicator_getBinaryVarSuperindicator
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsSuperindicator
 * Method:    getSlackConsSuperindicator
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsSuperindicator_getSlackConsSuperindicator
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipConsSuperindicator
 * Method:    transformMinUC
 * Signature: (J[Z)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipConsSuperindicator_transformMinUC
  (JNIEnv *, jobject, jlong, jbooleanArray);

#ifdef __cplusplus
}
#endif
#endif
