/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipBranchMostinf */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipBranchMostinf
#define _Included_de_zib_jscip_nativ_jni_JniScipBranchMostinf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipBranchMostinf
 * Method:    includeBranchruleMostinf
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipBranchMostinf_includeBranchruleMostinf
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
