/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipSepaCgmip */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipSepaCgmip
#define _Included_de_zib_jscip_nativ_jni_JniScipSepaCgmip
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipSepaCgmip
 * Method:    includeSepaCGMIP
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipSepaCgmip_includeSepaCGMIP
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
