/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipMessage */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipMessage
#define _Included_de_zib_jscip_nativ_jni_JniScipMessage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipMessage
 * Method:    messagehdlrCapture
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipMessage_messagehdlrCapture
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipMessage
 * Method:    messagehdlrRelease
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_de_zib_jscip_nativ_jni_JniScipMessage_messagehdlrRelease
  (JNIEnv *, jobject);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipMessage
 * Method:    messagehdlrSetData
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipMessage_messagehdlrSetData
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipMessage
 * Method:    messagehdlrSetLogfile
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipMessage_messagehdlrSetLogfile
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipMessage
 * Method:    messagehdlrSetQuiet
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipMessage_messagehdlrSetQuiet
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipMessage
 * Method:    messagePrintErrorHeader
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipMessage_messagePrintErrorHeader
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipMessage
 * Method:    messageSetErrorPrintingDefault
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipMessage_messageSetErrorPrintingDefault
  (JNIEnv *, jobject);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipMessage
 * Method:    messagehdlrGetData
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_zib_jscip_nativ_jni_JniScipMessage_messagehdlrGetData
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipMessage
 * Method:    messagehdlrGetLogfile
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_de_zib_jscip_nativ_jni_JniScipMessage_messagehdlrGetLogfile
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipMessage
 * Method:    messagehdlrIsQuiet
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_de_zib_jscip_nativ_jni_JniScipMessage_messagehdlrIsQuiet
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
