/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipSepaClosecuts */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipSepaClosecuts
#define _Included_de_zib_jscip_nativ_jni_JniScipSepaClosecuts
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipSepaClosecuts
 * Method:    includeSepaClosecuts
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipSepaClosecuts_includeSepaClosecuts
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipSepaClosecuts
 * Method:    setBasePointClosecuts
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipSepaClosecuts_setBasePointClosecuts
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
