/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipPropObbt */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipPropObbt
#define _Included_de_zib_jscip_nativ_jni_JniScipPropObbt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipPropObbt
 * Method:    includePropObbt
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipPropObbt_includePropObbt
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
