/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipPropVbounds */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipPropVbounds
#define _Included_de_zib_jscip_nativ_jni_JniScipPropVbounds
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipPropVbounds
 * Method:    includePropVbounds
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipPropVbounds_includePropVbounds
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipPropVbounds
 * Method:    isPropagatedVbounds
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_de_zib_jscip_nativ_jni_JniScipPropVbounds_isPropagatedVbounds
  (JNIEnv *, jobject, jlong);

/*
 * Class:     de_zib_jscip_nativ_jni_JniScipPropVbounds
 * Method:    execPropVbounds
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_de_zib_jscip_nativ_jni_JniScipPropVbounds_execPropVbounds
  (JNIEnv *, jobject, jlong, jboolean);

#ifdef __cplusplus
}
#endif
#endif
