/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipHeurFixandinfer */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipHeurFixandinfer
#define _Included_de_zib_jscip_nativ_jni_JniScipHeurFixandinfer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipHeurFixandinfer
 * Method:    includeHeurFixandinfer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipHeurFixandinfer_includeHeurFixandinfer
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
