/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipHeurRins */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipHeurRins
#define _Included_de_zib_jscip_nativ_jni_JniScipHeurRins
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipHeurRins
 * Method:    includeHeurRins
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipHeurRins_includeHeurRins
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
