/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipHeurActconsdiving */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipHeurActconsdiving
#define _Included_de_zib_jscip_nativ_jni_JniScipHeurActconsdiving
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipHeurActconsdiving
 * Method:    includeHeurActconsdiving
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipHeurActconsdiving_includeHeurActconsdiving
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
