/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_zib_jscip_nativ_jni_JniScipPresolGateextraction */

#ifndef _Included_de_zib_jscip_nativ_jni_JniScipPresolGateextraction
#define _Included_de_zib_jscip_nativ_jni_JniScipPresolGateextraction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_zib_jscip_nativ_jni_JniScipPresolGateextraction
 * Method:    includePresolGateextraction
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_de_zib_jscip_nativ_jni_JniScipPresolGateextraction_includePresolGateextraction
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
